### ISSUE TITLE
Import from Git repository

### ISSUE THREAD

**Issue by EJMFarrow** [maths/moodle-qbank_gitsync#3]
- Either take a list of filenames OR scan the directory, and sub-directories. Which of these makes the most sense? How does this tie in to sharing quizzes? #2 
- Import all questions in the files/directory.
- Return a JSON "manifest" linking Moodle questionid to filenames and write manifest back to the repro for safe-keeping.

**Comment by sangwinc** [comment]
The idea is that this recent project
https://github.com/maths/moodle-qbank_importasversion
will form an important component in resolving this part of the project.
