### ISSUE TITLE
Mismatch between CLI and server: please add a check!

### ISSUE THREAD

**Issue by sangwinc** [maths/moodle-qbank_gitsync#58]
I've just tried to use the new command

```php createwholecourserepo.php ...```

but I got the error

````
PHP Warning:  Undefined property: stdClass::$quizzes in /home/csangwin/Documents/gitsync/classes/create_repo.php on line 282
PHP Warning:  foreach() argument must be of type array|object, null given in /home/csangwin/Documents/gitsync/classes/create_repo.php on line 282
````

That's because I (obviously!) forgot to update the PHP scripts on my local moodle, to match the PHP script I'm using on the command line....   I wonder if we could have a simple version check of some kind in the protocol to at least warn a user of the mismatch.  I can see this being a common (for me) problem.

**Comment by sangwinc** [comment]
So in my case (above) checking something like the mismatch between plugin versions `2024052400` (server) and `2024121000` command line would have prompted me todate the server.

**Comment by EJMFarrow** [comment]
Good idea. I've put in a check that stops processing on the initial context check if the version doesn't match. Now on the dev branch.
